/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.refrig.ui;

/**
 *
 * @author gabup
 */
public class InicioSesion extends javax.swing.JFrame
{

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion()
    {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        iniciarBoton = new javax.swing.JButton();
        registrarseBoton = new javax.swing.JButton();
        salirBoton = new javax.swing.JButton();
        usuarioText = new javax.swing.JTextField();
        contrasenaText = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(74, 160, 9));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iniciarBoton.setBackground(new java.awt.Color(142, 197, 101));
        iniciarBoton.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        iniciarBoton.setText("Iniciar sesion");
        iniciarBoton.setBorderPainted(false);
        jPanel1.add(iniciarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        registrarseBoton.setBackground(new java.awt.Color(142, 197, 101));
        registrarseBoton.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        registrarseBoton.setText("Registrarse");
        registrarseBoton.setBorderPainted(false);
        registrarseBoton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                registrarseBotonActionPerformed(evt);
            }
        });
        jPanel1.add(registrarseBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        salirBoton.setBackground(new java.awt.Color(142, 197, 101));
        salirBoton.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        salirBoton.setText("Salir");
        salirBoton.setBorderPainted(false);
        salirBoton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                salirBotonActionPerformed(evt);
            }
        });
        jPanel1.add(salirBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));
        jPanel1.add(usuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 140, -1));
        jPanel1.add(contrasenaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 140, -1));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel3.setText("Usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 165, 59, -1));

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel4.setText("Contraseña");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 249, -1, -1));

        jPanel2.setBackground(new java.awt.Color(239, 206, 121));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/refrig/sources/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(33, 67, 30));
        jLabel2.setText("CocinaFácil");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(28, 28, 28))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirBotonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_salirBotonActionPerformed
    {//GEN-HEADEREND:event_salirBotonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirBotonActionPerformed

    private void registrarseBotonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_registrarseBotonActionPerformed
    {//GEN-HEADEREND:event_registrarseBotonActionPerformed
        new Registro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registrarseBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contrasenaText;
    private javax.swing.JButton iniciarBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton registrarseBoton;
    private javax.swing.JButton salirBoton;
    private javax.swing.JTextField usuarioText;
    // End of variables declaration//GEN-END:variables
}
