/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.refrig.ui;

/**
 *
 * @author gabup
 */
public class Registro extends javax.swing.JFrame
{

    /**
     * Creates new form Registro
     */
    public Registro()
    {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        regresarBoton = new javax.swing.JButton();
        registrarseBotonñ = new javax.swing.JButton();
        nombreTexto = new javax.swing.JTextField();
        apellidosTexto = new javax.swing.JTextField();
        fechaTexto = new javax.swing.JTextField();
        generoCaja = new javax.swing.JComboBox<>();
        correoTexto = new javax.swing.JTextField();
        contratexto = new javax.swing.JPasswordField();
        confirmarTexto = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(74, 160, 9));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(239, 206, 121));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/refrig/sources/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(33, 67, 30));
        jLabel2.setText("CocinaFácil");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(28, 28, 28))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel3.setText("Nombres");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel4.setText("Apellidos");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel5.setText("Confirmar contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel6.setText("Fecha nacimiento");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel7.setText("Genero");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel8.setText("Correo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel9.setText("Contraseña");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        regresarBoton.setBackground(new java.awt.Color(142, 197, 101));
        regresarBoton.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        regresarBoton.setText("Regresar");
        regresarBoton.setBorderPainted(false);
        regresarBoton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                regresarBotonActionPerformed(evt);
            }
        });
        jPanel1.add(regresarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        registrarseBotonñ.setBackground(new java.awt.Color(142, 197, 101));
        registrarseBotonñ.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        registrarseBotonñ.setText("Registrarse");
        registrarseBotonñ.setBorderPainted(false);
        jPanel1.add(registrarseBotonñ, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));
        jPanel1.add(nombreTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 130, -1));
        jPanel1.add(apellidosTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 130, -1));

        fechaTexto.setText("DD/MM/AAAA");
        fechaTexto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fechaTextoActionPerformed(evt);
            }
        });
        jPanel1.add(fechaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 100, -1));

        generoCaja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Masculino", "Femenino", "Otro" }));
        jPanel1.add(generoCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 120, -1));
        jPanel1.add(correoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 120, -1));
        jPanel1.add(contratexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 90, -1));
        jPanel1.add(confirmarTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fechaTextoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fechaTextoActionPerformed
    {//GEN-HEADEREND:event_fechaTextoActionPerformed
        fechaTexto.setText("");
    }//GEN-LAST:event_fechaTextoActionPerformed

    private void regresarBotonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_regresarBotonActionPerformed
    {//GEN-HEADEREND:event_regresarBotonActionPerformed
        new InicioSesion().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosTexto;
    private javax.swing.JPasswordField confirmarTexto;
    private javax.swing.JPasswordField contratexto;
    private javax.swing.JTextField correoTexto;
    private javax.swing.JTextField fechaTexto;
    private javax.swing.JComboBox<String> generoCaja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombreTexto;
    private javax.swing.JButton registrarseBotonñ;
    private javax.swing.JButton regresarBoton;
    // End of variables declaration//GEN-END:variables
}
